
---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---
## Loading and preprocessing the data
```{r, echo = TRUE}
setwd("C:\\Users\\Maha\\Desktop\\Training online\\Reproducible")

activity <- read.csv("activity.csv")
library(ggplot2)
library(dplyr)
### Size of data
dim (activity)[1] 
dim (activity)[2] 
### Type of data
str(activity)

### Summary of data
summary(activity)

```
## What is mean total number of steps taken per day?
```{r, echo = TRUE}
total_step <- aggregate(activity$steps, list(activity$date), FUN=sum)
colnames(total_step) <- c("Date", "Steps")

qplot(total_step$"Steps",geom="histogram",xlab="Total Steps",ylab="Counts",main="Total Steps Historgram")


mean(total_step$Steps, na.rm=TRUE)
median(total_step$Steps, na.rm=TRUE)

```
## What is the average daily activity pattern?
```{r, echo = TRUE}

step_time <- aggregate(steps~interval,data=activity,FUN=mean,na.action=na.omit)
step_time$time <- step_time$interval/100

g <- ggplot(step_time, aes(time, steps))
g+geom_line(col="blue")+ggtitle("Average steps per time interval")+xlab("Time")+ylab("Steps")+theme(plot.title = element_text(face="bold", size=12))


IT <- tbl_df(step_time)

IT %>% select(time, steps) %>% filter(steps==max(IT$steps))

```
## Imputing missing values
```{r, echo = TRUE}
Missind_Value <- tbl_df(activity)
Missind_Value %>% filter(is.na(steps)) %>% summarize(missing_values = n())

activity$CompleteSteps <- ifelse(is.na(activity$steps), round(step_time$steps[match(activity$interval, step_time$interval)],0), activity$steps)

activity_data_imputed <- data.frame(steps=activity$CompleteSteps, interval=activity$interval, date=activity$date)

Full_data_Steps <- aggregate(activity_data_imputed$steps,list(activity_data_imputed$date), FUN=sum)
colnames(Full_data_Steps) <- c("Date", "Steps")

g <- ggplot(Full_data_Steps, aes(Steps))
g+geom_histogram(col="brown")+ggtitle("Average steps per time interval")+xlab("Time")+ylab("Steps")+theme(plot.title = element_text(face="bold", size=12))


```
## Are there differences in activity patterns between weekdays and weekends?
```{r, echo = TRUE}
activity_data_imputed$RealDate <- as.Date(activity_data_imputed$date, format = "%Y-%m-%d")
activity_data_imputed$weekday <- weekdays(activity_data_imputed$RealDate)
activity_data_imputed$DayType <- ifelse(activity_data_imputed$weekday=='Saturday' | activity_data_imputed$weekday=='Sunday', 'weekend','weekday')

Steps_time_Day <- aggregate(steps~interval+DayType,data=activity_data_imputed,FUN=mean,na.action=na.omit)

Steps_time_Day$time <- Steps_time_Day$interval/100
m <- ggplot(Steps_time_Day, aes(time, steps))
m+geom_line(col="darkred")+ggtitle("Average steps per time interval: weekdays vs. weekends")+xlab("Time")+ylab("Steps")+theme(plot.title = element_text(face="bold", size=12))
```

